FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY iiko_etl/requirements.txt /tmp/iiko-etl-requirements.txt
RUN pip install --no-cache-dir -r /tmp/iiko-etl-requirements.txt

COPY iiko_etl ./iiko_etl

EXPOSE 8791

CMD ["uvicorn", "iiko_etl.etl_server.app.main:app", "--host", "0.0.0.0", "--port", "8791"]
